
----REQUETE 1
SELECT d.Month,d.Year,COUNT(a.id_accident) as NumberAccident FROM DW_ACCIDENT a,DW_DATE d  WHERE a.ID_DATE=d.ID_DATE GROUP BY ROLLUP (d.Month,d.YEAR);

----REQUETE 2

SELECT v.VEHICLETYPE,c.SEVERITY,COUNT(a.NUMBER_OF_CASUALTIES) as NUMBER_CASUALTY FROM DW_ACCIDENT a,DW_VEHICLE v,DW_CASUALTY c WHERE a.ID_VEHICLE=v.ID_VEHICLE AND a.ID_CASUALITY=c.ID_CASUALITY GROUP BY CUBE(v.VEHICLETYPE,c.SEVERITY);


---REQUETE 3 


SELECT l.URBAN,COUNT(a.id_accident) FROM DW_ACCIDENT a,DW_LOCATION l WHERE a.ID_LOCATION=l.ID_LOCATION GROUP BY l.URBAN; 

---- REQUETE 4


SELECT l.ROAD,c.SEVERITY,COUNT(a.id_accident) as NUMBER_CASUALTY FROM DW_ACCIDENT a,DW_LOCATION l,DW_CASUALTY c WHERE a.ID_LOCATION=l.ID_LOCATION AND a.ID_CASUALITY=c.ID_CASUALITY GROUP BY CUBE(l.ROAD,c.SEVERITY);

---- REQUETE 5 

SELECT v.VEHICLETYPE,v.PROPULSION_CODE,COUNT(a.id_accident) as NumberAccident FROM DW_ACCIDENT a,DW_VEHICLE v  WHERE a.ID_VEHICLE=v.ID_VEHICLE GROUP BY ROLLUP (v.VEHICLETYPE,v.PROPULSION_CODE);


---- REQUETE 6 
SELECT d.AGE_BAND,d.SEX_DRIVER,COUNT(a.id_accident) as NumberAccident FROM DW_ACCIDENT a,DW_DRIVER d  WHERE a.ID_DRIVER=d.ID_DRIVER GROUP BY ROLLUP (d.AGE_BAND,d.SEX_DRIVER);


---- REQUETE 7

SELECT c.CLASSCASUALITY,c.SEVERITY,COUNT(a.ID_ACCIDENT) FROM DW_ACCIDENT a,DW_CASUALTY c WHERE a.ID_CASUALITY=c.ID_CASUALITY GROUP BY ROLLUP (c.CLASSCASUALITY,c.SEVERITY);


---- REQUETE 8

SELECT l.CITY ,COUNT(a.ID_ACCIDENT) as NB_ACCIDENT FROM DW_ACCIDENT a,DW_LOCATION l WHERE a.ID_LOCATION=l.ID_LOCATION GROUP BY l.city ORDER BY NB_ACCIDENT DESC;



