CREATE TABLE DW_WEATHER(
   ID_WEATHER NUMBER(10) PRIMARY KEY,
   WeatherCondition VARCHAR2(100),
   LightCondition VARCHAR2(100)
   );


ALTER TABLE accident_tab ID_WEATHER DEFAULT NULL;

----CREATION D'UN TRIGGER ET D'UNE SEQUENCE POUR AUTO-INCREMENTER LA CLE PRIMAIRE 
CREATE SEQUENCE SEQUENCE_DW_WEATHER START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRIGGER_DW_WEATHER
BEFORE INSERT ON DW_WEATHER
FOR EACH ROW
DECLARE
BEGIN
   SELECT  SEQUENCE_DW_WEATHER.nextval into :new.ID_WEATHER from DUAL;
END;
/


-- REMPLISSAGE DE LA TABLE DE DIMENSION
INSERT INTO DW_WEATHER(WeatherCondition,LightCondition)
SELECT DISTINCT a.get_weather_condition(),a.get_light_condition()			
FROM accident_tab a;


