CREATE TABLE DW_LOCATION(
   ID_LOCATION NUMBER(10) PRIMARY KEY,
   City VARCHAR2(100),
   Urban VARCHAR2(100),
   Road VARCHAR2(100),
   Longitude VARCHAR2(100),
   Latitude VARCHAR2(100)
   );

----CREATION D'UN TRIGGER ET D'UNE SEQUENCE POUR AUTO-INCREMENTER LA CLE PRIMAIRE 
CREATE OR REPLACE SEQUENCE SEQUENCE_DW_LOCATION START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRIGGER_LOCATION
BEFORE INSERT ON DW_LOCATION 
FOR EACH ROW
DECLARE
BEGIN
   SELECT  SEQUENCE_DW_LOCATION.nextval into :new.ID_LOCATION from DUAL;
END;
/


-- REMPLISSAGE DE LA TABLE DE DIMENSION
INSERT INTO DW_LOCATION(City,Urban,Road,Longitude,Latitude)
SELECT a.get_city(),a.get_urban(),a.get_road(),a.get_longitude(),a.get_latitude()			
FROM accident_tab a;


